### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by volkmarkt** [massedge/wordpress-plugin-export-media-library#15] opened 2019-07-04 16:51 UTC
I installed this plugin in February and it worked fine. The I took it off. Now I installed it again freshly, but it doesn't. 
<img width="639" alt="Bildschirmfoto 2019-07-04 um 18 43 50" src="https://user-images.githubusercontent.com/52543729/60680796-0e5c0600-9e8d-11e9-9aa8-545c9baf297e.png">
I have WP 5.2.2, hosted at GoDaddy, PHP 7.2 and have no idea, why its not working. Is there any workaround or tip?

**Comment by andrejpavlovic** [comment] 2019-07-04 16:56
Maybe try an older version of the plugin. You'll find them at the bottom of:
https://wordpress.org/plugins/export-media-library/advanced/

**Comment by volkmarkt** [comment] 2019-07-04 17:25
I tried it out, Andrej, no success. Still the same error message. Could that have to do something with the use of Imagify?

**Comment by andrejpavlovic** [comment] 2019-07-04 18:19
Hmm, I just tried it now and it seems to be working fine... It could be some other plugin. Ideally you could disable all the plugins and see if it helps. Not sure I can be of much help here...

**Comment by LostInBrittany** [comment] 2019-07-10 08:16
I get the same problem, tried to disable plugins without success...

**Comment by oksohi** [comment] 2019-07-19 05:38
Hi! I'd really like to use this plugin but I can't find it.
I'm using wordpress.org with the latest version, and I loaded the plugin into the back end via ftp because Plugins don't automatically show on my dashboard these days. But I can see it there (when I'm asked to update other plugins), and when I go to activate, it says "Error: Current PHP version does not meet minimum requirements for Export Media Library." Your page says I need PHP version 7.0 or higher and my hosting provider (3iX) says I'm on 7.3.

**Comment by andrejpavlovic** [comment] 2019-07-22 17:29
@oksohi Your hosting provider may support PHP 7.3, but you probably need to enable it. You should look into seeing what is the actual PHP version running your site. You can use https://wordpress.org/plugins/debug-info/ plugin for that.

**Comment by andrejpavlovic** [comment] 2019-07-22 17:31
Duplicate of #13

**Closed by andrejpavlovic** 2019-07-22 17:31 UTC
