### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by Sprung831** [massedge/wordpress-plugin-export-media-library#13] opened 2019-05-31 14:59 UTC
I'm getting an ERR_INVALID_RESPONSE message.  

The webpage at https://www.XXXXXXXX.com/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.

**Comment by andrejpavlovic** [comment] 2019-05-31 15:58
This happens after you click Download Zip?

Can you provide me with the following:
PHP version
Wordpress Version
Plugin Version
Hosting provider

It might help me narrow down the problem.

**Comment by Sprung831** [comment] 2019-05-31 16:09
That’s correct.

See versions below.

Thanks,

[cid:image001.jpg@01D45587.A3521B00]
Steve Sprung
Product & Marketing Manager
262-330-8911 -Direct
262-432-0877 -Office
262-790-2177 -Fax
www.RTCProducts.com<http://www.RTCProducts.com>

**Comment by ActiveVentilationProducts** [comment] 2019-06-28 16:46
I just downloaded the plugin, and I get this same error. I thought perhaps it was because I was running it on a password-protected staging clone of my main site, but I turned off the password protection and I got the same error.

**Comment by Aldo-f** [comment] 2019-08-02 16:46
Same error.


---
PHP version: 7.3
Wordpress Version: 5.2.2
Plugin Version: 2.2.0 
Hosting provider: neostrada.nl

---

**Comment by antisocialmediamanager** [comment] 2019-08-07 20:23
same.

**Comment by slipsey1** [comment] 2019-08-22 17:11
Me too!

**Comment by Praisinghim247** [comment] 2019-09-25 14:41
Are you still working on this issue? I have an urgent need to pull media off our website and thought this would be our answer,  but I, too, received this message:

This site can’t be reachedThe webpage at https://holocaustremembranceassociation.org/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

Please help....

**Comment by andrejpavlovic** [comment] 2019-09-27 01:47
I've never been able to reproduce the issue myself, so I can't really tell what the problem could be.

**Comment by Praisinghim247** [comment] 2019-09-27 10:05
I used WP Manager, no problems downloading our huge media library.

Thanks
Joan

**Comment by BladeXR** [comment] 2019-10-03 18:09
Hi @andrejpavlovic, I'm like the rest of the people. Plugin not working when I click the download button. It gets a generic 500 error

**Comment by andrejpavlovic** [comment] 2019-10-18 17:34
I think at this point the only way I can debug this issue is if someone compresses their entire site and database and PMs the links to the files to me - that way I can see what is causing the problem first hand. As it is currently, I can't do much...

**Comment by seanjmcm** [comment] 2019-10-28 13:41
Same issue:

```
This site can’t be reachedThe webpage at https://mdcl.io/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

**Comment by seanjmcm** [comment] 2019-10-28 16:41
Got this email:

Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Export Media Library.

First, visit your website (https://mdcl.io/) and check for any visible issues. Next, visit the page where the error was caught (https://mdcl.io/wp-admin/upload.php?page=mass-edge-export-media-library) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special “recovery mode”. This lets you safely login to your dashboard and investigate further.

https://mdcl.io/wp-login.php?action=enter_recovery_mode&rm_token=**not putting it here ;-)**

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

Error Details ============= An error of type E_ERROR was caused in line 461 of the file /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/export-media-library/vendor/maennchen/zipstream-php/src/ZipStream.php. Error message: Out of memory (allocated 94515200) (tried to allocate 85737472 bytes)

**Comment by seanjmcm** [comment] 2019-10-28 16:42
Looks like a memory issue?

**Comment by andrejpavlovic** [comment] 2019-10-28 17:20
@seanjmcm It's possible. Try downloading without compressing.

**Comment by seanjmcm** [comment] 2019-10-28 17:40
I tried that first.  I've just used WinSCP to download the folder and that's ok so I'm finished but hopefully the above is of help to you. 
Ciao.
S

**Comment by atloar** [comment] 2019-11-04 08:26
Hi 
I have the same problem keep getting  error when trying to export media. Has anyone got a fix for this as I need to export my images.

The web page at https://moveathletica.com.au/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by DarkArtek** [comment] 2019-11-07 09:44
Same problem. EC2 Machine with 4gb ram.  PHP 7.3.5 , Memory: 1G

**Comment by andrejpavlovic** [comment] 2019-11-25 18:07
Latest version (3.0.0) has a small update that tries to address the memory issue. If someone can give that a try, let me know it works for you.

**Comment by andrejpavlovic** [comment] 2019-12-05 16:17
Closing due to lack of response.

**Closed by andrejpavlovic** 2019-12-05 16:17 UTC
