### ISSUE TITLE
ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by rsinusas** [massedge/wordpress-plugin-export-media-library#18] opened 2019-11-11 14:48 UTC
I have been trying for days and I keep getting

This site can’t be reachedThe webpage at https://www.XXXXXX.com/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by andrejpavlovic** [comment] 2019-11-25 17:56
Duplicate of #13

**Closed by andrejpavlovic** 2019-11-25 17:56 UTC
Labels: duplicate
